services:
  teashop:
    build:
      context: .
      args:
        - PYTHON_IMAGE_VERSION=${PYTHON_IMAGE_VERSION}
        - POETRY_VERSION=${POETRY_VERSION}
        - DEV_IMAGE=${DEV_IMAGE}
    image: georgysk/teashop:0.2.1
    volumes:
      - .:/opt/teashop
    stdin_open: true
    tty: true
